sudo: required
language: generic
services:
- docker
env:
  global:
  - IMAGE_NAME=LibertusDio/go-idmatch
  - secure: "cQ7MzsTLT0xSwLBhJCFjhf2l/7V+4jRn2n1lf7SL0RYIWYSauVA80WIPF2zaN5cumjAXRUwokg2y85kDvbmmJbrS117l2aTAsgkkQaKBld/rSTL8Tk1poEv77FzDLACoxrpsBZ01CzCskHvAzbf/jtFUC4+zvQiY7gio1ER7gXEGfyPKqgIxLHD3rHuRqwY89DPAYQA1r6pgYWVSCSnGHh+0DCjwtRB4BWMPi8ngGn/Zc9HpjMfW6ey6FDRzfNMovsnNYdk90pJC3ouTC4zYHew1GevuSTRK4zh3NZ0UiiCfnasTidcfipICniV7maI16194J16++TsvhTE7+Da8Mk/pAF4q6PkKKsRB7NbVUNpydk8AsnR9mn5ajLK2ujSN4mDNO/T3KEC14FXBnY41ExO13Z+TSsVGhQoBZamMJ8abc72g8koaZ9D7R1VjkqdTlIPbrEXXVsAV75sYZdYt9ZO+y/Dj841SaAE3/VJq/KABCRoZpkMYGLn5zFgFxrrU7YQ4FV3Vbm1SRsXn+/mfiFa/qHdCL3Hwo6biE3D0c4yHg93/YOKLmj4OHMvDEFWONCdrYDw3pRpnXNFuqjcdq+iyLkhILzpQokQbGtQBA48JUgd6z+RVue5pr48hQpS+D7BpfJxTcnGaS7VaZBICaneF8OgOtRUYbYXs4onRipA="
  - secure: "MRlLOHntBu7vXJCOKVioD5RS6bxK43NPflw7JhqkOEnyUaXLPVR+mh3t3fcCugiWm0MuBzU39kG+rQGwa6C53lmTvGx8f+3af0Fthoh77VFIw73v2U7Z++FgzwGGfL8E9N/S2TWjgZN+6SdjAz41Cy36FufvhQ1PpPPzK8REaKPVJLphMU4NzoKk0jGtygT4tXPB2u7InQ/YpUZ7MHyORWtCjXsq/JqpdgaoV5YCy/EGNdai9hn00mpYOA20KwjvSXnnt6mGGaa4il3TwYsYJGSkpwtogR3EXk2envgUfRv6xJShuLlIFBoNVaD5k5BstKrPLkCcjMUuiwVZOrkpUm+hd3BU35dEp6vbJ6KANq299hh8frwyirpzYmDw1tK1AONMT9IGiiOHuYH6E4rUvS7gaib/IwX43z2LQWDpTUjNUkbULAfCOJjueyhIjof8n6T4f+xvUe5lzdNp5af/4LJbJZE5gzaHuo2Wz0mdy7XwhxxBaJMx14j3QTqnudCq3Zpn4CuN5axxd/PknUl5X1eKAkLQZU2Got/2yjYBDWA75U7MnlMYJBKWDV9fphTUdrBBnzBG7durVYojlNje2d1DdvvpnHff1uRbEpKW6ucNG8UI0pJkIYMUceWcisAzqovqaB8pS5vnJvmIQgr1WbgvkCnyoGfrEZo7ONEMJaY="
before_deploy:
- docker login -u "$HUB_USER" -p "$HUB_SECRET"
- docker build -t "$IMAGE_NAME" .
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest"
  on:
    branch: master