sudo: required
language: generic
services:
- docker
env:
  global:
  - IMAGE_NAME=maddevsio/go-idmatch
  - secure: "CDEtZ4rXYMZif0OExDnDP/CPJhAvfZyCe9YBus1yBrZ/KS3HWEis8CptJ/+DShB8RYUtJtrWWOH11Qhf8O/DnaTp/JfRQpLb3Hdsh0qqqpqj+NFMdH5uudAc74NLLACzyy+XgAJLT5nEtGh41Ebntiq3CW0adz5hOr8JLodoyR5mzEDxgvkNZS8YW/EWX1pLHgHwsdciYpz5dA7t39ubap8IY4lfuOQRIU0NUaUytLxaAZzJ8WWujgdJflnIwlnXhzpc/4236vvUo7527qIp+OZoI9DSuRPGiOS0hGpMaDWrwbdMN0S8OzirwyJsGl6p7JrZXSuFXCwPK78N+c47Qsmd1r/5F64BT9qPGldr1Xf1d8/Fcz4T2Bk8BlvI5YIhTZ8SJ5JYP9Z0CbefvQUr6pHCSWBylnRlQ9qFjdMFnGakEcVL4P7OaJo3WZa5gcJgqEAEEGhGEWkdJYbsQEc3oG3TvYHvA7+NZ5/Y/CmrMUwTBDQ/ZuG2cysBUO+4KggGGbF1yrRuqIYufodaxVeMot4ymMj13bSZIFMRz+FZFP5q1vXfhz1F1mboQeK1o+6Nx/kCwNkyiEtHenbUR2x3eAMBh+p6QmaX0OKtbe7o/OywPUa1Dkd88srtYczBqtRmXuowkAlmA7I8z1ABl1cBR5b+JQsPAV99k4Zog6b/PoI="
  - secure: "DMmx2swuHFuYTGy3kShWHBd3tTt6Ql1SQvSx2eF5tbOsYTEQO84Xknnj2PES+KXdtxzO3aZH0XjuZ6j56D8bmxUNLFwD0gJn3vD+qgWJnEN2M4MzhnpjVYNTx+NcaAkKRoYz7AQPsv9Y30asIUaQFXxdUybh5TfpVlKeHxazbfonGq7AyWgzBsIiwNxtnSpNB+TIDEQSuCHAMA9Woc0cviOsM9cQp4tg4DnvbTt41OCyNBpsKBomYQ+IA4B96cfnUwBBL48vdbwsvPOG30JK3/bTKnotqx3uogasfUMDD/D2rRqMRyq2R6z8DjBkIY4J/ap2QIJJggTA3S2uCCw0hF1AzR4/g/6XyS40MZ6Jqxm95GaOMoSXaCM9qWk+HtWnYo8YgLXQn9tea0PLRMED/EsSXmY//JZY83LzsrePEkVQnUxGNSblNfOHQ8OnyCBw9Q/lshjVLXg8YdDY4xGUzAfv8ix49TNwnDxtnMM6QLjBnmKRs+6m+sJpHgsBefjUfm1CGh+l7tPF6G8Awyv6CYiAfvikvxTwVsGSChPjKUwIVZdwfa1LmGg7CSJyQm2mn1koWL67C4Ka2Dp4ohTnoOuznTIgIBUe4w10AGqlR4gYope84imOV+w+pQDvkkdqmD8vMH9fR1OY9anunAREjbyvtoH4gTUiLFP7wU2NjM8="
before_deploy:
- docker login -u "$HUB_USER" -p "$HUB_SECRET"
- docker build -t "$IMAGE_NAME" .
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest"
  on:
    branch: loginfix